### PR TITLE
Update main icons

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by varlesh** [comment]
Not draw 128px, because really not used on eOS

**Comment by artemanufrij** [comment]
What is the different?

**Comment by varlesh** [comment]
image

**Comment by artemanufrij** [comment]
I like the shadow... but could you make the background a little darker. here is elementary color palette 
http://danielfore.com/palette.html

**Comment by varlesh** [comment]
@artemanufrij You can modify palette, as like you... use sed for eay way/
I'm add gradient background, stroke, shadow and other little fixes/ open files on inkscape and compare... if needed

**Comment by SubhadeepJasu** [comment]
@artemanufrij Since you are planning on using this new icon, I want to confirm that you would want me to continue making the icon I was making.
image
image

**Comment by SubhadeepJasu** [comment]
Would I continue making it?
image

**Comment by SubhadeepJasu** [comment]
I am open to feedbacks.

**Comment by varlesh** [comment]
@artemanufrij Some examples:
image
Zoom 700%:
image

PS:Daniel palette used another tone... i'm confused :)

**Comment by varlesh** [comment]
@artemanufrij more Darker colors added:
image

**Comment by artemanufrij** [comment]
@varlesh sorry for the late answer. you made the icon and racktangles a little bit smaller. could you make the headphones and qualizer like "original" icon again (in all sizes)? then we could merge it.

**Comment by SubhadeepJasu** [comment]
@artemanufrij this is to confirm. Do I continue making the icon I was making?

**Comment by artemanufrij** [comment]
@SubhadeepJasu If I honest with you, I like headphones more than musical note.

**Comment by varlesh** [comment]
@artemanufrij updated

**Comment by varlesh** [comment]
i'm finished

**Comment by artemanufrij** [comment]
Wow I love it. I will merge it tommorow. ..

**Comment by SubhadeepJasu** [comment]
ok

**Comment by artemanufrij** [comment]
@varlesh could you take a look to https://github.com/artemanufrij/playmyvideos :smile:

**Pull request merged**
