### PR TITLE
Grammatical corrections for AppCenter appdata

### PR DESCRIPTION
**Pull request by imasaru**
Small grammatical corrections for the AppCenter entry.

### CODE REVIEW

**Comment by ryonakano** [comment]
I'm not sure this should be done whether in this PR or in a new one, but I think we should also update this line to "Listen to your music":

https://github.com/artemanufrij/playmymusic/blob/548cb200c3dd59739ee17a8ec1f9234576858748/data/com.github.artemanufrij.playmymusic.desktop.in#L4

**Comment by artemanufrij** [comment]
hey guys, thanks for your suggestions... I will ask a native speaker for correct grammar....

**Comment by ryonakano** [comment]
@imasaru This PR has a conflict which needs resolving. I think you should be able to resolve the conflict because you're author of this PR and have write access to it.

**Comment by ryonakano** [comment]
Oh, it looks like @artemanufrij fixed this grammar mistake in 00593b5528fc279f0f67163c603bea71a31cb95c, so we can close this one now.

**Comment by artemanufrij** [comment]
@ryonakano thanks for your feedback

**Comment by imasaru** [comment]
@ryonakano @artemanufrij Aye, I'm really sorry about this, guys! I need to whittle down my Watch subscriptions. Usually, I'm mired in a ton of irrelevant notifications and don't see the important ones.

Glad you got it fixed, and sorry for not replying sooner! 👍

**Pull request closed without merging**
