### PR TITLE
add missing cmake modules.

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Makes the application not dependent on elementary-cmake. Which makes it easier to build on other distros that don't have that package by default.

I would have added a PR to merge to meson directly, but I'm pretty busy these days. This will just allow me to finish the flatpak package as soon as possible. 
I might do the migration to meson later if you're interested ;)

### CODE REVIEW

**Comment by artemanufrij** [comment]
hey @bilelmoussaoui thank you for your PR. What's your opinion - should "molody" moved to meson?

**Comment by bilelmoussaoui** [comment]
Yes. Meson is easier to use and a faster alternative to cmake and autotools. The syntax is pretty clear

**Comment by artemanufrij** [comment]
@bilelmoussaoui could you help me to move to meson? Then I would have an example for Cinema and Memories…

**Comment by bilelmoussaoui** [comment]
Will take a look as soon as possible.

**Comment by artemanufrij** [comment]
@bilelmoussaoui thank you very much!

**Comment by bilelmoussaoui** [comment]
Gonna close this one and open a new one with meson support instead.

**Pull request closed without merging**
