### PR TITLE
internet-radio-symbolic icon

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by varlesh** [comment]
Symbolic icon for Radios. Draw as like elementary style:

image

**Comment by artemanufrij** [comment]
@varlesh thank you for your PR. could you rename the icon like `artemanufrij.playmymusic…`. It's a rule in elementary for third-party-apps...

**Comment by varlesh** [comment]
ok

**Comment by artemanufrij** [comment]
additionaly you can make a PR for elementary icon set.

**Comment by artemanufrij** [comment]
@varlesh 

https://github.com/elementary/icons

**Comment by varlesh** [comment]
@artemanufrij It's can not be merged, because playmusic 3d party app

**Comment by artemanufrij** [comment]
I mean a separate PR. only with your icon!

**Comment by varlesh** [comment]
Ok, i try...

**Comment by varlesh** [comment]
@artemanufrij Need close this PR https://github.com/elementary/icons/pull/367 ?

**Comment by artemanufrij** [comment]
@varlesh no! I will switch to default icon set after marging your branch in elementary/icons... until it not happens I will use this branch.

**Comment by varlesh** [comment]
ok... wait

**Comment by varlesh** [comment]
@artemanufrij PR merged :)

**Comment by artemanufrij** [comment]
@varlesh I see :)

**Pull request merged**
