### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by Hedronmx**
New icon for the app in all sizes(16, 24, 32, 48, 64 , 128)

### CODE REVIEW

**Comment by artemanufrij** [comment]
@Hedronmx thank you very much for your PR! Could you pull the icons in .svg format?

**Comment by Hedronmx** [comment]
For some reason I'm having problems with the svg export. Let me try to find another way to export it 😄

**Comment by Hedronmx** [comment]
Done!

**Comment by artemanufrij** [comment]
hey @Hedronmx . It's not a svg. It's a png file embeded in svg. Icons should be separate in each size. Here is a guide
https://elementary.io/docs/human-interface-guidelines#size


bildschirmfoto von 2017-10-10 19 12 08

**Comment by SubhadeepJasu** [comment]
@artemanufrij Did you see the app icon I posted on google plus. Do I send you here as svg?

**Comment by artemanufrij** [comment]
marged a new icon #52

**Pull request closed without merging**
