### PR TITLE
Close "Edit Album Properties" by single X click

### PR DESCRIPTION
**Pull request by sfesenko**
Fix for issue #114

### CODE REVIEW

**Comment by artemanufrij** [comment]
Hey @sfesenko. Thank you for your PR. I'm going to test it tonight.

**Comment by artemanufrij** [comment]
@sfesenko Just tested your PR. It works fine. Could you remove whole `switch` statement please?
use just:
```
editor.run ();
editor.destroy ();
```

**Comment by sfesenko** [comment]
done, also fixed similar issue with "artist properties" dialog

**Comment by artemanufrij** [comment]
@sfesenko thank you very much. I will pull a new release next weekend!

**Comment by sfesenko** [comment]
@artemanufrij you are welcome )

**Pull request merged**
